# -*- coding: utf-8 -*-
"""TASK2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15A_Zch_1fwCP9iNr0gyZvmv10pXYdQHP
"""

import pandas as pd

df = pd.read_csv("/content/Data.csv")

df.head()

#Perform Operations
#Filtering Data Based on Conditions

filtered_df = df[df['Y-Kappa'] > 25]
filtered_df

df_filled = df.fillna(0)  # Replace NaN with 0
df_filled

df_ffill = df.fillna(method='ffill')
df_ffill

df_dropped = df.dropna()
df_dropped

df_dropped_cols = df.dropna(axis=1)
df_dropped_cols

# Calculate Summary Statistics

summary_stats = df.describe()
summary_stats

mean_y_kappa = df['Y-Kappa'].mean()
mean_y_kappa

median_y_kappa = df['Y-Kappa'].median()
median_y_kappa

std_dev_y_kappa = df['Y-Kappa'].std()
std_dev_y_kappa

